var cbx={ver:840,lp:0};window.tbl=null;window.cbm=null;window.op=null;if(document.currentScript){var matches=document.currentScript.src.match(/_(.*)\.js/);matches&&1<matches.length&&(cbx.build=matches[1])}
window.c2init=function(){cbx.debug.log("Starting");cbx.notifyParent("loading");var a=document.forms.cbox;window.f=cbx.$frm=a;cbx.gsUser=cbx.getGSObject(s_id+":user");cbx.gsPrefs=cbx.getGSObject("_:prefs");if(s_uo)cbx.updateKey(a.key.value),cbx.gsUser.set("nme",a.nme.value!=t1?a.nme.value:t1);else{var b=cbx.gsUser.get("key"),c=cbx.gsUser.get("nme"),d=cbx.gsUser.get("eml");b&&cbx.updateKey(b);c&&(a.nme.value=c);a.eml&&d&&(a.eml.value=d)}!s_uo||""!=a.nme.value&&""!=a.key.value||(a.pst.value=t0);window.onbeforeunload=
function(){};window.onfocus=function(){cbx.notifyParent("focus")};window.onblur=function(){cbx.notifyParent("blur")};s_sn&&(cbx.setSndVol(cbx.gsPrefs.get("sndVol")),window.setTimeout(function(){cbx.audio.setup(snuri)},1500));window.setTimeout(function(){cbx.rsz()},10);window.onresize=cbx.rsz;document.body.onselectstart=function(a){a=a||window.event;a=(a=a.target||a.srcElement)&&a.tagName.toLowerCase();return"textarea"!=a&&"input"!=a?!1:!0};try{(cbm=parent["cboxmain"+s_no])&&cbm.ready&&window.cbmready(cbm,
!0)}catch(e){}};
window.cbmready=function(a,b){var c=function(a){cbx.debug.log(a,"CBMREADY")};c("Called "+(b?"locally":"remotely")+": importing");var d=cbx.$frm;d?(window.cbm=a,a.document.getElementById("mt")&&a.document.getElementById("mt").tBodies?window.tbl=a.document.getElementById("mt").tBodies[0]:c("Could not find message table"),!a.frld&&1*window.ctme+5<1*a.ftme&&(a.frld=!0,window.setTimeout(function(){document.location.reload(!0)},1E3)),cbx.lp=Math.max(cbx.lp,1*a.lpid),s_on&&a.onu&&cbx.aonliners(1*a.onu),
a.exp&&(d.pst.value=a.exp,d.pst.disabled="true",d.sub.disabled="true"),a.nme&&d.nme.value==t1&&(d.nme.value=a.nme),a.eml&&d.eml&&d.eml.value==t5&&(d.eml.value=a.eml),cbm.onscroll=cbx.onScroll,cbx.disableAutoScroll=!1,window.setInterval(cbx.autoScroll,500),cbm.onresize=function(){cbx.autoScroll()},cbx.delban(),cbx.upd_tms(),ar_reset(),a.onunload=function(){a=cbx.$body=null},cbx.notifyParent("ready")):c("Race detected. Bailing.")};"undefined"===typeof JSON&&(window.JSON={parse:function(){},stringify:function(){}});
cbx.getGSObject=function(a,b){var c,d;try{var e=localStorage.getItem("cbx:"+a);e&&(d=JSON.parse(e))&&d.val&&(c=d.val)}catch(f){}d||(d={});c||(c={});return{get:function(a){return c[a]},set:function(e,f){if(!c[e]||c[e]!==f){c[e]=f;d.val=c;var m=(new Date).getTime()/1E3|0;d.ctime?d.mtime=m:d.ctime=m;b&&(d.ttl=1*b);try{localStorage.setItem("cbx:"+a,JSON.stringify(d))}catch(l){}}},toString:function(){return JSON.stringify(c)}}};
cbx.notifyParent=function(a,b){if(!window.postMessage)return!1;window.parent.postMessage(JSON.stringify({event:""+a,data:b,serial:s_no}),"*")};cbx.debug={loadTime:(new Date).getTime(),history:[],log:function(a,b){var c=cbx.debug;c.history.push({time:(((new Date).getTime()-cbx.debug.loadTime)/1E3).toFixed(3),msg:a,group:b?b:""});50<c.history.length&&c.history.shift()},stringify:function(a){if("string"===typeof a||"number"===typeof a)return a;var b=[],c;for(c in a)b.push(c+": "+a[c]);return b.join(", ")}};
cbx.debugOverlay={ovr:null,updTmr:null,visible:!1,update:function(){var a=cbm.document.getElementById("cbx_debug_msg"),b=["<b>Version:</b>  "+cbx.ver+" build "+cbx.build+" in "+document.compatMode+"<br>","<b>Namespace:</b>  "+s_phost+"-"+s_id+"-"+s_tid+" ("+s_no+") "+("https:"==document.location.protocol?"HTTPS":"")+"<br>","<b>User Agent:</b> "+navigator.userAgent+"<br>","<b>Time:</b> "+(new Date).getTime()+", scomp: "+cbx.unixTime()+"<br>","<b>Prefs:</b> "+cbx.gsPrefs.toString()+"<br>","<b>User:</b> "+
cbx.gsUser.toString()+"<br>","<b>LP ID:</b> "+cbx.lp+"<br>","<b>Scroll lock:</b> "+scrollFollow+"<br>","<b>ARMGR state:</b> "+cbx.arMgr.state+", wait: "+cbx.arMgr.backoff+"<br>","<b>WS/FL/LP/RP state:</b> "+wsconn.state+" / "+flconn.state+" / "+cbx.lpconn.state+" / "+cbx.repl.state+"<br>","<b>Repl:</b> client "+cbx.repl.clientID+"; slave of "+cbx.repl.masterID+"<br>","<b>Presence:</b> "+cbx.presMgr.state+"<br>","<b>LP:</b> "+cbx.debug.stringify(cbx.lpconn)+"<br>","<b>--- Log ---</b><br>"],c;for(c in cbx.debug.history){var d=
cbx.debug.history[c];b.push(d.time+" ["+d.group+"] "+d.msg+"<br>")}a.innerHTML=b.join("");cbx.autoScroll()},show:function(){if(cbm){var a=cbm.document.getElementById("cbx_debug_msg");null===a&&(a=cbm.document.createElement("div"),a.id="cbx_debug_msg",a.style.color="#666",a.style.fontSize="12px",a.style.fontFamily="monospace",a.style.wordWrap="break-word",a.style.background="#fff",a.style.padding="6px");s_sd?cbm.document.body.appendChild(a):cbm.document.body.insertBefore(a,cbm.document.body.firstChild);
this.visible=!0}},hide:function(){var a=cbm.document.getElementById("cbx_debug_msg");if(!a||!this.visible)return!1;cbm.document.body.removeChild(a);this.updTmr&&window.clearInterval(this.updTmr);this.updTmr=null;this.visible=!1},toggle:function(){this.visible?this.hide():(this.show(),this.update())},autorefresh:function(){this.hide();this.show();this.updTmr=window.setInterval(this.update,300);this.update()}};cbx.cmdHistory=[];cbx.cmdCursor=0;
cbx.cmdExec=function(a){if("//"!==a.substring(0,2))return!1;var b=cbx.$frm;b.pst.onkeydown=function(a){a=a||window.event;"INPUT"===b.pst.tagName&&(38==a.keyCode&&cbx.cmdCursor+1<cbx.cmdHistory.length&&(cbx.cmdHistory[cbx.cmdCursor]=b.pst.value,b.pst.value=cbx.cmdHistory[++cbx.cmdCursor],a.preventDefault()),40==a.keyCode&&cbx.cmdHistory.length&&cbx.cmdCursor&&(cbx.cmdHistory[cbx.cmdCursor]=b.pst.value,b.pst.value=cbx.cmdHistory[--cbx.cmdCursor],a.preventDefault()))};a!==cbx.cmdHistory[0]&&(cbx.cmdHistory[0]=
a,cbx.cmdHistory.unshift(""),10<cbx.cmdHistory.length&&cbx.cmdHistory.pop());cbx.cmdCursor=0;a=a.substring(2).split(" ");switch(a[0]){case "debug":switch(a[1]){case "watch":cbx.debugOverlay.autorefresh();break;default:cbx.debugOverlay.toggle()}break;case "reload":switch(a[1]){case "all":cbm.location.reload(!0);default:window.location.reload(!0)}break;case "ping":cbx.doPing();break;case "login":case "profile":p_open();break;case "smilies":pop("smilies",640,400,1);break;case "captcha":cbx.doCaptcha();
break;case "scroll":switch(a[1]){default:cbx.disableAutoScroll=!cbx.disableAutoScroll}break;case "loadcss":cbx.loadCSS(cbm,a[1]);cbx.loadCSS(window,a[1]);break;case "loadsound":cbx.audio.setup(a[1]);break;case "ignore":break;case "sticky":break;case "tetris":var c=window.open("","","width=400, height=600, resizable=yes");c.document.write('<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body id="bdy" style="position:absolute;margin:0;width:100%;height:100%;"></body></html>');
c.document.close();c.document.title="TETRIS!";var d=c.document.getElementById("bdy");c.onTetrisReady=function(a){a=new a(d);c.onresize=a.redraw;c.onblur=a.pause;c.onfocus=a.resume;a.start()};a=c.document.createElement("script");a.src="//static.cbox.ws/jsc/tetris.js?1";d.appendChild(a);break;case "kill":switch(a[1]){case "ws":wsconn.socket&&wsconn.socket.close();wsStart=function(){};break;case "fl":cbx.flash.close();startFlashRelay=function(){};break;default:set_status("Unknown argument")}break;default:set_status("Unknown command <b>"+
a[0]+"</b>.")}return!0};cbx.loadCSS=function(a,b){var c=a.document.getElementsByTagName("head")[0],d=a.document.createElement("link"),e=c.getElementsByTagName("link"),f;for(f in e)"text/css"===e[f].type&&c.removeChild(e[f]);d.setAttribute("rel","stylesheet");d.setAttribute("type","text/css");d.setAttribute("href",b);c.appendChild(d)};
cbx.rpcProcess=function(a,b){if("string"===typeof a&&a.length){for(var c=a.split("\n"),d=0;d<c.length;d++){var e=c[d];if(!(1>e.length)){var f=[];"<"==e.substring(0,1)&&(f=e.substring(1).split("="));if(0<f.length)switch(f[0]){case "del":cbx.proc_rpc_del(f[1]);break;case "updusrcnt":cbx.aonliners(f[1]);break;case "ping":f[1]&&add_peer_post("Ping reply (WS): "+Math.round((new Date).getTime()-1*f[1])+" ms");break;default:b&&b(f[0],f[1])}else cbx.parseMsg(e),cbx.delban(),cbx.upd_tms()}}window.setTimeout(function(){cbx.repl.sendmessage(a)},
0)}};cbx.doPing=function(){var a=(new Date).getTime(),b="";4===wsconn.state&&(b="&ping="+a+"&cid="+wsconn.id+"&chash="+wsconn.hash);cbx.xhr("./?"+s_rq+"&sec=ar"+b,null,function(b,d){if(!b||d)"L-timeout"==d?set_status("Ping timeout"):set_status(d);else{var e=(new Date).getTime()-a;add_peer_post("Ping reply (XHR): "+Math.round(e)+" ms")}},5E3)};var relax=!1;
window.do_refresh=function(){if(null==tbl)return!0;set_status(t9);cbx.autoScroll(!0);if(relax)return window.setTimeout("set_status(t10)",500),!1;relax=!0;window.setTimeout(function(){relax=!1},1E4);cbx.xhr("./?"+s_rq+"&sec=ar&p="+cbx.lp+"&c="+cbx.unixTime(),null,function(a,b){!a||b?set_status(b):cbx.aj_proc(a)||set_status(t10)});return!1};
window.do_post=function(){var a=cbx.$frm,b=a.pst.value;if(cbx.cmdExec&&cbx.cmdExec(b))return a.pst.value="",a.pst.focus(),!1;if(!cb_checkform()||a.sub.disabled)return!1;set_status(t23);cbx.autoScroll(!0);null==window.tbl&&a.submit();a.pst.value="";a.pst.focus();if(null===window.tbl)return!1;for(var c={aj:cbx.ver,lp:cbx.lp,pst:b},d="nme eml key ekey fkey pic auth captme capword caphash".split(" "),e=0;e<d.length;e++){var f=d[e];!a[f]||""===a[f].value||"eml"==f&&a[f].value==t5||(c[f]=a[f].value)}cbx.xhr("./?"+
s_rq+"&sec=submit",c,function(c,d){c=c||"";var e=c.split("\n")[0].split("\t");if(!c||e[0]||d){if(a.pst.value==t3||""==a.pst.value)a.pst.value=b;set_status(t12+" "+(e[0]||d))}else set_status(""),a.pst.focus(),cbx.gsUser.set("nme",a.nme.value!=t1?a.nme.value:""),a.eml&&cbx.gsUser.set("eml",a.eml.value!=t5?a.eml.value:"");cbx.aj_proc(c)})||(a.pst.value=b);return!1};
cbx.aj_proc=function(a){var b=a.split("\n"),c=b[0].split("\t");if(!a)return!1;for(a=b.length-1;0<a;a--)cbx.parseMsg(b[a]);0<1*c[1]&&cbx.aonliners(c[1]);c[3]&&cbx.updateKey(c[3]);(a=Math.round(1*c[2]-(new Date).getTime()/1E3))&&cbx.gsPrefs.set("timeDelta",a);c[5]&&cbx.gsUser.set("lpid",1*c[5]);b.length-1&&(cbx.upd_tms(),cbx.delban());return b.length-1};
cbx.updateKey=function(a){if(a&&(cbx.$frm.key.value=a,cbx.gsUser.get("key")!==a)){var b=cbx.gsUser.get("lvl"),c=0;if(!s_uo)c=1*a.substring(a.length-1,a.length);else if(s_uo)if(3==s_uo){var d=cbx.$frm;cbx.xhr("./?"+s_rq+"&sec=getlvl&n="+esc(d.nme.value)+"&k="+d.key.value,null,function(a,b){if(!a)return!1;cbx.gsUser.set("lvl",1*a);cbx.delban()})}else c=1;cbx.gsUser.set("lvl",c);cbx.gsUser.set("key",a);cbx.$frm.nme.value!=t1&&cbx.gsUser.set("nme",cbx.$frm.nme.value);c!==b&&cbx.delban()}};
window.ar_reset=function(){cbx.debug.log("ar_reset called");s_ar&&!cbx.arMgr.state&&cbx.arMgr.run();s_on&&!cbx.presMgr.state&&cbx.presMgr.run()};
cbx.presMgr={state:0,pingIval:6E4,lastPingTme:0,run:function(){var a=function(){var a=(new Date).getTime();cbx.presMgr.lastPingTme&&a-cbx.presMgr.lastPingTme>1.5*cbx.presMgr.pingIval&&cbx.debug.log("Ping delayed by "+((cbx.presMgr.pingIval-a+cbx.presMgr.lastPingTme)/1E3|0)+" sec","PRES");cbx.presMgr.lastPingTme=a;cbx.xhr("./?"+s_rq+"&sec=ar&p="+cbx.lp+"&c="+cbx.unixTime(),null,function(a,b){cbx.presMgr.state=!a||b?1:3})};cbx.presMgr.state=1;window.setTimeout(function(){cbx.debug.log("Starting ping.",
"PRES");a();cbx.presMgr.state=2;window.setInterval(function(){a()},cbx.presMgr.pingIval)},4E3)}};
cbx.arMgr={state:0,backoff:2E3,lpIval:null,tmr:null,run:function(){cbx.arMgr.state=1;var a=function(){cbx.arMgr.backoff=Math.min(36E4,Math.floor(cbx.arMgr.backoff*(1.5+Math.random())))},b=function(){cbx.arMgr.backoff=Math.floor(1E3*(1.5+Math.random()))},c=function(a){cbx.debug.log(a,"ARMGR")},d=function(a,b){c(cbx.arMgr.state+"->"+a+" "+b);a!=cbx.arMgr.state&&(cbx.arMgr.state=a)},e=function(a,b){null!==cbx.arMgr.tmr&&(window.clearTimeout(cbx.arMgr.tmr),cbx.arMgr.tmr=null);a&&(cbx.arMgr.tmr=window.setTimeout(function(){c("Timer fired");
a()},b))};cbx.arMgr.lpIval&&(window.clearInterval(cbx.arMgr.lpIval),cbx.arMgr.lpIval=null);cbx.arMgr.lpIval=window.setInterval(function(){3<=cbx.arMgr.state?cbx.lpStop():cbx.lpStart()},15E3);var f=!1,g=function(){d(2,"Attempting WS");a();e(f?g:h,1E4+cbx.arMgr.backoff);cbx.wsconn.onstatechange=function(){2===cbx.arMgr.state&&4===cbx.wsconn.state?(d(4,"WS connected"),b(),e(function(){f=!0;c("Locking WS")},3E4)):4===cbx.arMgr.state&&0==cbx.wsconn.state&&(d(0,"WS disconnected. Retrying in "+cbx.arMgr.backoff),
cbx.wsconn.onstatechange=null,e(g,cbx.arMgr.backoff))};wsStart(window.wsuri)},h=function(){d(2,"Attempting FL");a();e(g,1E4+cbx.arMgr.backoff);cbx.flconn.onstatechange=function(){2===cbx.arMgr.state&&4===cbx.flconn.state?(d(4,"FL connected"),b(),e(null)):4===cbx.arMgr.state&&0==cbx.flconn.state&&(d(0,"FL disconnected"),cbx.flconn.onstatechange=null,e(h,cbx.arMgr.backoff))};startFlashRelay()};(function(){d(1,"Attempting Repl");e(g,5E3);cbx.repl.onstatechange=function(){var a=4===cbx.arMgr.state||2===
cbx.arMgr.state||0===cbx.arMgr.state;a&&4===cbx.repl.state?d(4,"Repl connected; have upstream"):1===cbx.arMgr.state&&4===cbx.repl.state?(d(3,"Repl connected"),e(null),cbx.repl.onmessage=function(a){cbx.rpcProcess(a)}):a&&4>cbx.repl.state?d(4,"Repl disconnected; have upstream"):3===cbx.arMgr.state&&4>cbx.repl.state&&(d(1,"Repl disconnected"),cbx.repl.onmessage=null,e(g,5E3))};cbx.repl.start(s_id+"_"+s_tid)})()}};cbx.lpconn={enabled:!0,state:0,tmeLastRequest:0,curWait:0,lastErr:null,numMessages:0,numRequests:0};
cbx.lpStop=function(){cbx.lpconn.enabled=!1};cbx.lpStart=function(){var a=cbx.lpconn.enabled&&cbx.lpconn.state;cbx.lpconn.enabled=!0;a||cbx.lpLoop()};
cbx.lpLoop=function(){var a=cbx.lp;if(0<cbx.lpconn.state)return!1;cbx.lpconn.state=1;cbx.lpconn.numRequests++;cbx.lpconn.tmeLastRequest=(new Date).getTime();var b=null;window.XDomainRequest?(b=new XDomainRequest,cbx.debug.log("Creating XDR object","LP")):(b=new XMLHttpRequest,cbx.debug.log("Creating XHR object","LP"));var c=!1,d=function(a){c||(c=!0,cbx.lpconn.lastErr=null,a=(new Date).getTime()-cbx.lpconn.tmeLastRequest,cbx.lpconn.curWait=Math.max(2E3,8E3-a)+Math.floor(5E3*Math.random()),window.setTimeout(function(){cbx.lpconn.state=
0;cbx.lpconn.enabled&&cbx.lpLoop()},cbx.lpconn.curWait),(a=b.responseText)?(a=a.substring(1)||"",cbx.rpcProcess(a),cbx.lpconn.numMessages++):cbx.lpconn.lastErr="Empty")};b.onload=d;b.onerror=d;b.onreadystatechange=function(){4==b.readyState&&d()};b.timeout=32E4;a=lpuri+"?id="+s_id+"_"+s_tid+"&ev="+a;b.open("GET",a);window.setTimeout(function(){b.send()},0);cbx.debug.log("OPENING "+a,"LP");return!0};
cbx.flash={obj:null,readyState:0,load:function(){window.fl_ready=function(){cbx.flash.readyState=2;cbx.flash.onready()};window.fl_gotconn=function(){cbx.flash.onopen()};window.fl_pclosed=function(){cbx.flash.onclose()};window.fl_gotmsg=function(a){cbx.flash.onmessage(a)};cbx.flash.obj=loadSWF("ARswf",window.fluri);cbx.flash.readyState=1},open:function(){cbx.flash.obj&&1<cbx.flash.readyState?cbx.flash.obj.doConn():cbx.debug.log("Open called on not-ready Flash!","FLA")},close:function(){cbx.flash.obj&&
1<cbx.flash.readyState?cbx.flash.obj.endConn():cbx.debug.log("Close called on not-ready Flash!","FLA")},onready:function(){},onmessage:function(a){},onopen:function(){},onclose:function(){}};
var flconn={id:null,hash:null,pool:null,state:0,numAttempts:0,numCommands:0,numMessages:0,onstatechange:null},startFlashRelay=function(){var a=null,b=function(a){if(a!=flconn.state&&(flconn.state=a,flconn.onstatechange))flconn.onstatechange()},c=function(b,c){null!=a&&(window.clearTimeout(a),a=null);b&&(a=window.setTimeout(function(){cbx.debug.log("Timer fired","FLAR");b()},c))},d=function(){cbx.debug.log("Failed","FLAR");flconn.pool=null;flconn.id=null;flconn.hash=null;b(0);c(null)};cbx.flash.onclose=
function(){cbx.debug.log("Closed","FLAR");b(0);d()};var e=function(){flconn.curAttempts++;cbx.debug.log("Opening","FLAR");c(d,1E4);cbx.flash.open();b(1)};cbx.flash.onopen=function(){b(2);c(d,1E4)};cbx.flash.onmessage=function(a){flconn.numMessages++;4===flconn.state&&c(d,18E4);cbx.rpcProcess(a,function(a,e){flconn.numCommands++;"pool"==a&&(cbx.debug.log("Registered","FLAR"),flconn.pool=e,c(d,18E4),b(4));"hash"==a&&(flconn.hash=e);"id"==a&&(flconn.id=e);flconn.id&&flconn.hash&&2==flconn.state&&(c(d,
1E4),b(3),cbx.debug.log("Registering","FLAR"),(new Image).src="./?"+s_rq+"&sec=relayreg&cid="+flconn.id+"&chash="+flconn.hash+"&m=fl&t="+(new Date).getTime())})};0===cbx.flash.readyState?(cbx.debug.log("Loading","FLAR"),cbx.flash.onready=function(){cbx.debug.log("Loaded","FLAR");e()},cbx.flash.load()):e()};cbx.flconn=flconn;
var wsconn={id:null,hash:null,pool:null,state:0,tmeAttempted:0,tmeOpened:0,tmeHalfEst:0,tmeCompleted:0,numAttempts:0,curAttempts:0,curBackoff:0,numCommands:0,numMessages:0,log:[],onstatechange:null,socket:null,tmr:null};cbx.wsconn=wsconn;
var wsStart=function(a){var b=function(a){cbx.debug.log(a,"WS")},c=function(a){if(a!=wsconn.state&&(wsconn.state=a,wsconn.onstatechange))wsconn.onstatechange()},d=function(a,c){null!==wsconn.tmr&&(window.clearTimeout(wsconn.tmr),wsconn.tmr=null);a&&(wsconn.tmr=window.setTimeout(function(){b("Timer fired");a()},c))},e=function(a){var b={"\\\\":"\\","&amp;":"&","&lt;":"<","&gt;":">","&quot;":'"',"&#039;":"'"};return a.replace(/(\\\\)|(&amp;)|(&lt;)|(&gt;)|(&quot;)|(&#039;)/g,function(a){return b[a]})};
try{wsconn.tmeAttempted=(new Date).getTime();wsconn.numAttempts++;wsconn.curAttempts++;b("OPENING "+a);var f=function(){d(null);0<wsconn.state&&(g.close(),c(0));wsconn.id=null;wsconn.hash=null;wsconn.pool=null};c(1);d(f,1E4);wsconn.socket&&(wsconn.socket.onclose=function(){},wsconn.socket.onerror=function(){},wsconn.socket.close(),wsconn.socket=null);wsconn.socket=new WebSocket(a);var g=wsconn.socket;g.onopen=function(){c(2);b("OPEN");d(f,5E3);wsconn.tmeOpened=(new Date).getTime();wsconn.curAttempts=
0};g.onclose=function(a){b("CLOSE "+(a.wasClean?"CLEAN":"UNEXPECTED")+" ("+a.code+") "+a.reason);c(0);f()};g.onerror=function(a){b("ERROR");f()};g.onmessage=function(a){wsconn.numMessages++;4===wsconn.state&&d(f,18E4);a=e(a.data);cbx.rpcProcess(a,function(a,e){wsconn.numCommands++;"pool"==a&&(b("Registered downlink"),c(4),wsconn.pool=e,d(f,18E4),wsconn.tmeCompleted=(new Date).getTime());"hash"==a&&(wsconn.hash=e);"id"==a&&(wsconn.id=e);null!==wsconn.id&&null!==wsconn.hash&&2===wsconn.state&&(b("Registering downlink"),
c(3),d(f,5E3),wsconn.tmeHalfEst=(new Date).getTime(),(new Image).src="./?"+s_rq+"&sec=relayreg&cid="+wsconn.id+"&chash="+wsconn.hash+"&m=ws&t="+(new Date).getTime())})}}catch(h){return c(0),b("Caught exception: "+h.message),!1}};window.togglear=function(a){};cbx.aonliners=function(a){a*=1;var b=document.getElementById("onliners");a&&b&&(b.innerHTML=a+"&nbsp;"+(1==a?t7:t8))};var scrollFollow=!0,scrollHeightPrev=null;
cbx.autoScroll=function(a){var b=cbm.document.getElementById("bdy");b&&!cbx.disableAutoScroll&&(a&&(scrollFollow=!0),a=Math.max(cbm.document.body&&cbm.document.body.scrollHeight,b&&b.scrollHeight,cbm.document.documentElement&&cbm.document.documentElement.scrollHeight),scrollFollow?s_sd?cbm.scrollTo(0,a):cbm.scrollTo(0,0):!s_sd&&scrollHeightPrev&&cbm.scrollBy&&cbm.scrollBy(0,a-scrollHeightPrev),scrollHeightPrev=a)};
cbx.onScroll=function(){var a=cbm.document.getElementById("bdy"),b=Infinity,c=0;cbm.document.documentElement&&(b=cbm.document.documentElement.clientHeight,c=cbm.document.documentElement.scrollTop);b=Math.min(b,a.clientHeight);c=Math.max(c,a.scrollTop);scrollFollow=s_sd&&c+b>a.scrollHeight-10?!0:!s_sd&&10>c?!0:!1};cbx.rszMargin=0;cbx.rszYMargin=0;cbx.rszH=0;cbx.rszW=0;
cbx.rsz=function(a){var b=cbx.$frm,c=document.documentElement.clientWidth,d=document.documentElement.clientHeight;if(!d||!c)cbx.debug.log("Bailed","RSZ");else if(c!==cbx.rszW||d!==cbx.rszH||!0===a){document.documentElement.style.position="absolute";document.documentElement.style.height="100%";document.documentElement.style.width="100%";document.documentElement.style.overflow="hidden";document.documentElement.style.margin="0";document.documentElement.style.padding="0";document.body.style.padding="0";
document.body.style.margin="0";var e=document.getElementsByTagName("table");if(e.length){e[0].style.width="auto";b.nme&&(b.nme.style.boxSizing="content-box",b.nme.style.MozBoxSizing="content-box",b.nme.style.webkitBoxSizing="content-box");b.eml&&(b.eml.style.boxSizing="content-box",b.eml.style.MozBoxSizing="content-box",b.eml.style.webkitBoxSizing="content-box");b.pst&&(b.pst.style.boxSizing="content-box",b.pst.style.MozBoxSizing="content-box",b.pst.style.webkitBoxSizing="content-box");b.sub&&(b.sub.style.boxSizing=
"content-box",b.sub.style.MozBoxSizing="content-box",b.sub.style.webkitBoxSizing="content-box");var f=cbx.rszMargin,e=cbx.rszYMargin;cbx.rszH=d;cbx.rszW=c;cbx.debug.log("Dims "+c+","+d+" "+f+","+e,"RSZ");if(b.nme&&b.eml&&!s_fa){b.nme.style.width="0";b.eml.style.width="0";var g=b.eml.offsetLeft+b.eml.offsetWidth;b.nme.style.width=Math.max(Math.ceil(c/2-g/2-f/2),1)+"px";b.eml.style.width=Math.max(Math.floor(c/2-g/2-f/2),1)+"px"}else b.nme&&(b.nme.style.width="0",b.nme.style.width=c-f-b.nme.offsetWidth-
b.nme.offsetLeft+"px"),b.eml&&(b.eml.style.width="0",b.eml.style.width=c-f-b.eml.offsetWidth-b.eml.offsetLeft+"px");s_fa?(b.pst.style.width="0",b.pst.style.width=c-f-b.pst.offsetWidth-b.pst.offsetLeft+"px"):(b.pst.style.width="0",b.pst.style.width=c-f-b.sub.offsetLeft-b.sub.offsetWidth+"px");1<s_fl&&(b.pst.style.height="0",s_fa||(b.sub.style.height="0",b.sub.style.display="none"),b.pst.style.display="none",f=d-document.getElementsByTagName("table")[0].offsetHeight,b.sub.style.display="",b.pst.style.display=
"",s_fa||(b.sub.style.height=f-b.sub.offsetHeight-e+"px"),b.pst.style.height=f-b.pst.offsetHeight-e+"px");b=document.getElementsByTagName("table")[0].offsetWidth+document.getElementsByTagName("table")[0].offsetLeft-c;d=document.getElementsByTagName("table")[0].offsetHeight+document.getElementsByTagName("table")[0].offsetTop-d;(b||d)&&!0!==a&&(cbx.rszMargin+=b,cbx.rszYMargin+=d,0>b&&(cbx.rszMargin=0),0>d&&(cbx.rszYMargin=0),window.setTimeout(function(){cbx.rsz(!0)},10))}}};
window.cb_checkform=function(){var a=cbx.$frm;return a.pst.value==t3?(set_status(t4),a.pst.focus(),!1):s_uo?!0:a.nme.value==t1?(set_status(t2),a.nme.focus(),!1):a.eml&&""!=a.eml.value&&a.eml.value!=t5&&0>=a.eml.value.lastIndexOf(".")&&0>=a.eml.value.lastIndexOf("@")?(set_status(t6),a.eml.focus(),!1):!0};function frmfocus(a,b){a.value==b&&(a.value="")}function frmblur(a,b){""==a.value&&(a.value=b)}
window.pop=function(a,b,c,d){var e=window.open("./?"+s_rq+"&sec="+a,"cb"+s_id+a.substring(0,3),"width="+b+", height="+c+", toolbar=no, scrollbars="+d+", status=no, resizable=yes");try{window.setTimeout(function(){var a=screen.height;e.moveTo(screen.width/2-b/2-100,a/2-a/4);e.focus()},10)}catch(f){}};window.crtn=function(a){var b=cbx.$frm;return 13==(window.event&&window.event.keyCode||a.keyCode||a.which)?(do_post()&&b.submit(),!1):!0};
function p_open(){var a=cbx.$frm;""==a.nme.value||a.nme.value==t1?(a.nme.focus(),alert(t2)):pop("profile&n="+esc(a.nme.value)+"&k="+a.key.value,480,320,0)}
function esc(a){return encodeURIComponent?encodeURIComponent(a):function(a){function c(a){function b(a,c){a+=c;return"%"+(16>a?"0":"")+a.toString(16).toUpperCase()}var c;c=127>=a?1:2047>=a?2:3;for(var d="",e=1;e<c;e++)d=b(a&63,128)+d,a>>>=6;return d=b(a,[0,192,224][c-1])+d}for(var d="",e=0;e<a.length;e++){var f=a.charCodeAt(e);if(128>f)var g=String.fromCharCode(f),d=-1!="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_.!~*'()".indexOf(g)?d+g:d+c(f);else d+=c(f)}return d}(a)}
cbx.unixTime=function(){var a=cbx.gsPrefs.get("timeDelta")||0;return Math.round((new Date).getTime()/1E3)+a};
cbx.xhr=function(a,b,c,d){var e=null,f=null;d=d||2E4;if(window.XMLHttpRequest)e=new XMLHttpRequest;else if(window.ActiveXObject)try{e=new ActiveXObject("Msxml2.XMLHTTP")}catch(g){try{e=new ActiveXObject("Microsoft.XMLHTTP")}catch(h){}}if(!e)return!1;var m="-";e.onreadystatechange=function(){if(4==e.readyState){m=e.status;window.clearTimeout(f);var a=" ("+e.readyState+":"+m+")";if(0==e.status)return l(t14+"L-network"+a);if(200!=e.status)return l(t14+"R-server"+a);var b=e.responseText,d=b.substring(0,
1),b=b.substring(1);if("1"!=d&&"0"!=d)return l(t14+"R-chksum"+a);if("0"==d)return l("R-"+b);c(b,null)}};e.onerror=function(){l("L-connection")};var l=function(a){a=a||"L-timeout";window.clearTimeout(f);null!==e&&(e.onreadystatechange=function(){},e.abort(),e=null);c(null,a)},f=window.setTimeout(l,d);e.open(b?"POST":"GET",a,!0);e.setRequestHeader("Accept","*/*");e.responseType="text";if(b){e.setRequestHeader("Content-Type","application/x-www-form-urlencoded");a=[];for(var k in b)a.push(k+"="+esc(b[k]));
e.send(a.join("&"))}else e.send();return!0};function set_status(a,b){var c=[];c[0]=b?-1:0;c[1]=0;c[2]="";c[3]="";c[4]=0;c[5]="";c[6]=a;add_post(c)}cbx.parseMsg=function(a){a=a.split("\t");0<a[0]&&1*a[0]>cbx.lp&&(cbx.lp=1*a[0]);add_post(a)&&(cbx.notifyParent("message",null),cbx.newMessageAsync())};cbx.newMessageTmr=null;cbx.newMessageAsync=function(){cbx.newMessageTmr||(s_sn&&cbx.audio.play(cbx.audioVol),cbx.newMessageTmr=window.setTimeout(function(){cbx.newMessageTmr=null},1E3))};
var add_peer_post=function(a){var b=[-2];b[1]=cbx.unixTime();b[2]="-";b[3]="[Server]";b[4]=0;b[5]="";b[6]=a;b[8]=32;add_post(b);cbx.upd_tms()};window.op=0;
function add_post(a){var b={id:a[0],unixtime:a[1],datestr:a[2],namehtml:a[3],userlevel:a[4],emlurlimg:a[5],msghtml:a[6],imgurl:a[7],bad_flags:a[8]},c=function(a){cbx.debug.log(a,"MSG")},d=function(a){return(a=cbm.document.getElementById(a))?a.rowIndex:null},e=function(a){var b=[];if(0==a.id||-1==a.id)return b.push('<div align="center">'+a.msghtml+"</div>"),b.join("");if(s_av){var c=a.emlurlimg.substring(a.emlurlimg.length-4);if(a.imgurl)b.push('<img src="http://'+a.imgurl+'" class="pic">');else if(".gif"==
c||".jpg"==c||".png"==c)b.push('<img src="'+a.emlurlimg+'" class="pic">'),a.emlurlimg=""}1<s_dt&&b.push('<div class="dtxt'+h+'" id="t'+a.unixtime+'" '+(s_rt?'dir="ltr"':"")+">"+a.datestr+"</div>");a.bad_flags&32&&b.push('<div class="dtxt'+h+'">('+t15+")</div>");a.emlurlimg&&b.push('<a href="'+a.emlurlimg+'" target="_blank">');b.push("<b");1==s_dt&&b.push(' title="'+a.datestr+'"');c="nme ";switch(a.userlevel){case "1":c+="pn_std";break;case "2":c+="pn_reg";break;case "3":c+="pn_mod";break;case "4":c+=
"pn_adm"}b.push(' class="'+c+'"');s_rt&&b.push(' dir="ltr"');b.push(">"+a.namehtml+"</b>");a.emlurlimg&&b.push("</a>");b.push(": "+a.msghtml);return b.join("")};if(cbm&&tbl&&cbm.document&&cbm.document.body){if(!a||7>a.length)return c("Badly formed; ignoring"),!1;if(0<b.id&&cbm.document.getElementById(b.id))return c("Duplicate; ignoring"),!1;a=tbl.rows.length;var f=!1,g=!1;cbm.document.getElementById(0)&&(c("Removing temp msg at "+d(0)),tbl.deleteRow(d(0)),a--);if(b.msghtml){var h="2",d=null;if(0<
a){(1==a&&!s_sd||1<a)&&-1==tbl.rows[0].id&&(f=!0);(1==a&&s_sd||1<a)&&-1==tbl.rows[a-1].id&&(g=!0);var m=tbl.rows[a-1].cells[0],l=tbl.rows[0].cells[0],k=0<a-(g?1:0)-(f?1:0)?tbl.rows[a-1-(g?1:0)].cells[0]:null,n=0<a-(g?1:0)-(f?1:0)?tbl.rows[f?1:0].cells[0]:null;s_sd?(d=tbl.insertRow(a-(g?1:0)),a++,h=null!=k?"stxt"==k.className?"2":"":"2",a-(g?1:0)-(f?1:0)>s_mp&&0!=b.id&&-1!=b.id&&(f&&(l.className="stxt"==l.className?"stxt2":"stxt"),tbl.deleteRow(0+(f?1:0)),a--),op=tbl.rows[f?1:0].id):(d=tbl.insertRow(f?
1:0),a++,h=null!=n?"stxt"==n.className?"2":"":"2",a-(g?1:0)-(f?1:0)>s_mp&&0!=b.id&&-1!=b.id&&(g&&(m.className="stxt"==m.className?"stxt2":"stxt"),tbl.deleteRow(a-1-(g?1:0)),a--),op=tbl.rows[a-1-(g?1:0)].id)}else d=tbl.insertRow(0);a=d.insertCell(-1);d.id=b.id;a.className="stxt"+h;a.innerHTML=e(b);c("Inserted message "+b.id);cbx.autoScroll();cbm.document.getElementById("jsdiv")&&(b=cbm.document.getElementById("jsdiv"),c=b.innerHTML,c=c.replace(/&amp;/g,"&"),eval(c),b.parentNode.removeChild(b),b=null);
return!0}c("Empty message; ignoring")}else c("DOM not available; ignoring")}var updTmsInt=null;
cbx.upd_tms=function(){if(3!=s_dt)return!0;for(var a=cbx.unixTime(),b=t16,c=cbm.document.getElementsByTagName("div"),d=[2592E3,604800,86400,3600,60,1],e=0;e<c.length;e++)if("dtxt"==c[e].className.substring(0,4)&&"t"==c[e].id.substring(0,1)){var f=a-1*c[e].id.substring(1);0>f&&(f=0);60>f&&(f=5*Math.ceil(f/5));for(var g=0;6>g;g++){var h=0;if(1<f/d[g]){f/=d[g];h=10-2*g;break}}c[e].title||(c[e].title=c[e].innerHTML);f=Math.round(f);c[e].innerHTML=t24.replace("%d",f).replace("%s",b[1==f?h:h+1])}null===
updTmsInt&&(updTmsInt=window.setInterval(cbx.upd_tms,5E3))};var lnkd=[];
cbx.delban=function(){var a=!1;cbx.updateKey(cbx.$frm.key.value);if(tbl){var b=cbx.gsUser.get("lvl"),c=cbx.gsUser.get("lpid");2<b&&(a=!0);for(var d=tbl.rows.length,e=0;e<d;e++){var f=tbl.rows[e];if(!(1>f.id)){var g=f.cells[0];lnkd[f.id]||(lnkd[f.id]=!0,g.innerHTML=g.innerHTML.replace(/(div>|pic\">|^)<(a|b)/i,'$1<span class="modtools" id="mod_'+f.id+'"></span><$2'));var h=cbm.document.getElementById("mod_"+f.id);h&&(h.innerHTML="",(a||s_ld&&f.id==c&&f.id==cbx.lp&&1<b)&&function(b){var c=document.createDocumentFragment(),
d=document.createElement("a");d.title=t17;d.href="javascript:void(0)";d.innerHTML="[&times;]&nbsp;";d.onclick=function(){cbx.del(b);return!1};c.appendChild(d);if(a){var e=document.createElement("a");e.title=t18;e.href="javascript:void(0)";e.innerHTML="[o]&nbsp;";e.onclick=function(){cbx.ban(b);return!1};e.onmouseover=function(){cbx.getip(b,e)};c.appendChild(e)}h.appendChild(c)}(f.id))}}}};
cbx.ban=function(a){var b=cbx.$frm,c=prompt(t21,"7 days");null!=c&&cbx.xhr("./?"+s_rq+"&sec=delban&n="+esc(b.nme.value)+"&k="+b.key.value+"&ban="+a+"&dur="+esc(c),null,function(a,b){b&&set_status(b);if(!a)return!1;a=a.split("\t");alert(a[1])})};cbx.del=function(a){var b=cbx.$frm;cbx.xhr("./?"+s_rq+"&sec=delban&n="+esc(b.nme.value)+"&k="+b.key.value+"&del="+a,null,function(a,b){b&&set_status(b);if(!a)return!1;cbx.del_proc(a)})};
cbx.del_proc=function(a,b){var c=tbl.rows.length;isNaN(b)&&(b=a);if(isNaN(a))return!1;for(var d=Math.min(a,b),e=Math.max(b,a),f=0,g=0;g<c&&tbl.rows[g];g++)1*tbl.rows[g].id>=1*d&&1*tbl.rows[g].id<=1*e&&(tbl.rows[g].cells[0].innerHTML='<div align="center"><i>'+t22+"</i></div>",tbl.rows[g]._deleted=!0,f++);return f};
cbx.proc_rpc_del=function(a){a=a.split(",");for(var b,c,d=0;d<a.length;d++)0>a[d].indexOf("_")?(b=parseInt(a[d]),isNaN(b)||cbx.del_proc(b)):(c=a[d].split("_"),b=parseInt(c[0]),c=parseInt(c[1]),isNaN(b)||isNaN(c)||cbx.del_proc(b,c))};var gips=[];cbx.getip=function(a,b){var c=cbx.$frm;gips[a]||(cbx.xhr("./?"+s_rq+"&sec=getip&n="+esc(c.nme.value)+"&k="+c.key.value+"&i="+a+"&r="+(new Date).getTime(),null,function(c,e){if(!c||e)return gips[a]=!1;b&&(b.title=t18+" (IP: "+c+")")}),gips[a]=!0)};
window.togglesnd=function(){var a=cbx.audioVol;switch(a){case 0:a=100;break;case 20:a=0;break;default:a=20}cbx.setSndVol(a);cbx.audio.play(a)};cbx.setSndVol=function(a){var b=0,c="off",d=document.getElementById("sndctrl");"undefined"===typeof a&&(a=cbx.audioVol);cbx.audioVol=a;switch(a){case 20:b=16;c="min";break;case 100:b=32,c="max"}d.className="Vol_"+c;d.style.left=-1*b+"px";cbx.gsPrefs.set("sndVol",a)};var titleT=null;
function titleflash(){if(0!=s_pp){var a=!1,b=0;parent.document.title="New message! - Cbox";titleT&&window.clearInterval(titleT);titleT=window.setInterval(function(){parent.document.title=a&&0==foc?"New message! - Cbox":"Cbox";a=a?!1:!0;(13<b++||0!=foc)&&window.clearInterval(titleT)},2E3)}}
var loadSWF=function(a,b){function c(a,b){return'<param name="'+a+'" value="'+b+'">'}window.document.getElementsByTagName("html");var d,e;d={name:a,id:a,src:b,quality:"high",allowScriptAccess:"always",bgcolor:"#ffffff",pluginspage:"http://www.macromedia.com/go/getflashplayer",title:"FL",type:"application/x-shockwave-flash",hasPriority:"true",width:1,height:1};e={position:"absolute",width:"8px",height:"8px",bottom:"0px",left:"-10px",overflow:"hidden","z-index":"10000"};var f="",g;for(g in d)f+=g+'="'+
d[g]+'" ';var h="";for(g in e)h+=g+": "+e[g]+"; ";d=['<object style="'+h+'" id="'+a+'" data="'+b+'" type="'+d.type+'" title="'+d.title+'" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0">',c("movie",b),c("AllowScriptAccess",d.allowScriptAccess),c("quality",d.quality),c("bgcolor",d.bgcolor),c("hasPriority",d.hasPriority),"<embed "+f+">","</object>"].join("");e=document.getElementById("flash_"+a)||document.createElement("div");
e.id="flash_"+a;document.body.appendChild(e);e.innerHTML=d;return document[a]};cbx.audioVol=100;
cbx.audio=function(){var a=function(a){cbx.debug.log(a,"AUDIO")};return{play:function(){a("Play called but not configured.")},setup:function(b){a("Setup called with "+b);var c=null,d=function(){window.soundManager={_externalInterfaceOK:function(d){a("SWF: ExternalInterface online! Version: "+d);window.setTimeout(function(){c._createSound("cbxsnd",1,!1)},100);window.setTimeout(function(){a("Flash: loading "+b+".mp3");c._load("cbxsnd",b+".mp3",!0,!1,!1)},500)},sounds:{cbxsnd:{_onload:function(b){b?
(a("SWF: Loaded - configuring for play."),cbx.audio.play=function(b){a("Flash play called at volume "+b);c._setVolume("cbxsnd",b);c._start("cbxsnd",1,0,!1)}):a("SWF: Load failed - not switching play")},_onfinish:function(){a("SWF: Got onfinish")}}}};cbx.audio.play=function(b){a("Play waiting on flash")};a("Attempting to load Flash object...");var c=loadSWF("SMswf",window.smuri)};if(!("Audio"in window))return a("No Audio object found - fast fallback."),d(),!1;var e=null,c=new Audio,f=function(){window.clearTimeout(h);
c?(a("Ready: Canplaythrough duration "+c.duration+". Setting play() handler"),cbx.audio.play=function(b){e?a("Play ongoing."):0!=b&&(e=window.setTimeout(function(){a("Play timeout. Falling back.");d()},5E3),cbx.audio.playStart=(new Date).getTime(),c.volume=b/100,c.play())},c.removeEventListener("canplaythrough",f,!1)):a("Ready fired but object destroyed.")},g=".ogg";c.canPlayType&&c.canPlayType('audio/ogg; codecs="vorbis"').replace(/no/,"")||(g=".mp3");a("Audio object created; chose "+g);var h=window.setTimeout(function(){a("Load timeout. Falling back.");
c=null;d()},5E3);c.addEventListener("canplaythrough",f,!1);c.addEventListener("error",function(b){a("Got error. Falling back");window.clearTimeout(h);e&&window.clearTimeout(e);c=null;d()},!1);c.addEventListener("timeupdate",function(a){c.currentTime&&null!==e&&(window.clearTimeout(e),e=null)},!1);a("Setting source: "+b+g);c.setAttribute("src",b+g)}}}();
cbx.repl=function(){var a="repl:",b=0,c="xxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;return("x"==a?b:b&3|8).toString(16)}),d=function(a){if(a!==b&&(b=a,k.state=b,k.onstatechange))k.onstatechange()},e=0,f=function(){var b=(new Date).getTime(),f=localStorage.getItem(a+":master"),g=null;try{g=JSON.parse(f)}catch(h){}f=function(){localStorage.setItem(a+":master",JSON.stringify({id:c,tme:b}))};k.masterID=null;g&&g.id?g.tme<b-2*(b-e)?(f(),d(3)):g.id!==c?(k.masterID=g.id,l(),d(4)):(f(),
d(2)):(d(1),f());e=b},g=0,h=null,m=!0,l=function(c){if(4===b){var d=null,e={};if(c&&c.key){if(c.key!==a+":buffer")return;d=c.newValue;e=JSON.parse(d)||{}}else try{d=localStorage.getItem(a+":buffer"),e=JSON.parse(d)||{}}catch(f){return}if(e&&e.pos!==h)if(h=e.pos,m)m=!1;else if("undefined"!==typeof e.msg&&k.onmessage)k.onmessage(e.msg)}},k={start:function(d){0<b||"string"!==typeof d||1>d.length||(a+=d,k.clientID=c,window.setTimeout(f,0),window.setInterval(f,2E3),window.addEventListener?(window.addEventListener("storage",
l),window.addEventListener("unload",k.stop)):(window.document.attachEvent("onstorage",l),window.attachEvent("onunload",k.stop)))},stop:function(){4!==b&&(localStorage.removeItem(a+":master"),localStorage.removeItem(a+":buffer"),d(0))},onmessage:function(){},sendmessage:function(d){4!==b&&(g++,localStorage.setItem(a+":buffer",JSON.stringify({msg:d,pos:c+g})))},pump:l,state:null,onstatechange:function(){},clientID:null,masterID:null};return k}();window.delban=cbx.delban;window.aonliners=cbx.aonliners;
